#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
LLM-assisted cell type annotation helpers.

This module keeps LLM use outside the deterministic scoring path. CellClick
calculates COSG marker genes and marker gene scores first, then these helpers
package the score table and marker evidence for an LLM to interpret.
"""

import json
import re

import pandas as pd


MARKER_GENE_SCORE_ALGORITHM_DESCRIPTION = """
CellClick Cell Identification algorithm:
1. Marker genes for the selected cell cluster are identified by COSG. COSG
   provides an expression specificity score for each candidate marker gene.
2. Reference marker genes are collected from marker databases such as
   CellMarker 2.0, singleCellBase, and CellStar. For each reference cell type,
   CellClick stores a marker gene confidence score (MGC) as geneWeight.
3. For a candidate reference cell type r and selected cluster c, CellClick
   compares the COSG marker set Gc with the reference marker set Gr. Genes in
   the overlap Gc,r = Gc intersect Gr provide the direct evidence.
4. In the current implementation, the marker gene score for each reference cell
   type is calculated as:
      score(r|c) =
        sum_over_overlap(MGC(g,r))
        *
        sum_over_overlap(COSG_score(g,c) / sum_COSG_scores_for_used_genes)
   where the first term reflects published/reference marker support and the
   second term reflects how specifically the overlapping genes mark the current
   cluster according to COSG.
5. Higher scores indicate stronger support for annotating the selected cluster
   as the corresponding reference cell type. The LLM should treat the score as
   ranking evidence, not as a calibrated probability.
"""

CELL_SCORE_ALGORITHM_DESCRIPTION = """
CellClick Reference Comparison cell score algorithm:
1. Given a marker gene set Gc for a defined/query cell type Cc, and a marker
   gene set Gt obtained by COSG for a reference cell type Ct, CellClick
   calculates CellScore(ci | Cc, Ct, Gc, Gt) for each cell ci from Cc to
   estimate the reliability of annotating ci, and therefore Cc, as Ct.
2. For each reference marker gene gjt in Gt, CellClick combines three evidence
   terms:
   - GS(Gc, gjt): similarity between the query marker set Gc and gjt, based on
     cosine similarity of gene expression across all cells and mean expression
     across cell clusters.
   - RES(Gc, gjt | Cc): relative expression specificity of gjt compared with
     Gc in the query cluster Cc, using COSG specificity scores.
   - EAD(Gc, gjt | ci): expression abundance difference of gjt compared with
     the mean expression of Gc in cell ci, transformed by a sigmoid-like
     function with scale factor k = 0.5 by default.
3. CellScore is the average over reference genes in Gt of
   GS(Gc, gjt) * RES(Gc, gjt | Cc) * EAD(Gc, gjt | ci). When gjt is already in
   Gc, the GS, RES, and EAD terms are treated as 1.
4. The violin plot generated by buildCellScorePlot shows the cell score
   distribution for candidate reference cell types. A higher cell score
   distribution indicates that the expression patterns of genes in Gt and Gc
   are more similar, supporting greater reliability for annotating Cc as Ct.
5. The LLM should treat cell scores as comparative evidence for annotation
   validation, not as calibrated probabilities.
"""


SYSTEM_PROMPT = """
You are assisting cell type annotation for single-cell or spatial omics data.
Use only the evidence provided by CellClick. Do not invent expression results,
genes, species, tissue source, or literature claims that are not present in the
input. If evidence is ambiguous, say so and keep the annotation conservative.
Return concise JSON.
"""


def MarkerGeneScores_cal(*args, **kwargs):
    from scripts.adata_processor.annotation_eval import MarkerGeneScores_cal as _impl

    return _impl(*args, **kwargs)


def _split_ref_cell_type(ref_cell_type):
    parts = str(ref_cell_type).split("_", 1)
    if len(parts) == 1:
        return "", parts[0]
    return parts[0], parts[1]


def _json_safe(value):
    if pd.isna(value):
        return None
    if hasattr(value, "item"):
        return value.item()
    return value


def _series_to_gene_records(series, max_genes=50):
    if series is None:
        return []
    records = []
    for gene, score in series.iloc[:max_genes].items():
        records.append({"gene": str(gene), "cosg_score": _json_safe(score)})
    return records


def _candidate_gene_evidence(ref_cell_type, geneWeight, markerSeries, max_genes=20):
    if geneWeight is None or markerSeries is None or ref_cell_type not in geneWeight.index:
        return {
            "reference_genes": [],
            "overlap_genes": [],
            "cosg_unique_genes": [],
            "weighted_overlap_genes": [],
        }

    marker_genes = list(markerSeries.index)
    reference_genes = [gene for gene in geneWeight.columns if geneWeight.loc[ref_cell_type, gene] > 0]
    overlap_genes = [gene for gene in marker_genes if gene in set(reference_genes)]
    cosg_unique_genes = [gene for gene in marker_genes if gene not in set(reference_genes)]

    weighted = []
    for gene in overlap_genes:
        weighted.append(
            {
                "gene": str(gene),
                "mgc": _json_safe(geneWeight.loc[ref_cell_type, gene]),
                "cosg_score": _json_safe(markerSeries.loc[gene]),
                "combined_weight": _json_safe(geneWeight.loc[ref_cell_type, gene] * markerSeries.loc[gene]),
            }
        )
    weighted = sorted(weighted, key=lambda item: item["combined_weight"], reverse=True)

    return {
        "reference_genes": [str(gene) for gene in reference_genes[:max_genes]],
        "overlap_genes": [str(gene) for gene in overlap_genes[:max_genes]],
        "cosg_unique_genes": [str(gene) for gene in cosg_unique_genes[:max_genes]],
        "weighted_overlap_genes": weighted[:max_genes],
    }


def build_marker_gene_score_llm_annotation_evidence(
    marker_gene_scores_cal,
    geneWeight=None,
    markerSeries=None,
    context=None,
    top_n=10,
    max_genes=50,
):
    if isinstance(marker_gene_scores_cal, dict):
        scores = marker_gene_scores_cal.get("scores")
        score_details = marker_gene_scores_cal.get("score_details")
        top_candidate_summary = marker_gene_scores_cal.get("top_candidate_summary") or {}
        geneWeight = geneWeight if geneWeight is not None else marker_gene_scores_cal.get("geneWeight")
        markerSeries = markerSeries if markerSeries is not None else marker_gene_scores_cal.get("markerSeries")
        geneWeightFull = marker_gene_scores_cal.get("geneWeightFull")
        background = marker_gene_scores_cal.get("background")
    else:
        scores = marker_gene_scores_cal
        score_details = None
        top_candidate_summary = {}
        geneWeightFull = None
        background = None

    if scores is None:
        scores = pd.Series(dtype=float)
    if not isinstance(scores, pd.Series):
        scores = pd.Series(scores)

    if score_details is not None and isinstance(score_details, pd.DataFrame) and len(score_details) > 0:
        candidate_df = score_details.head(top_n).copy()
    else:
        candidate_df = None

    evidenceGeneWeight = geneWeightFull if geneWeightFull is not None else geneWeight
    scores = scores.sort_values(ascending=False).iloc[:top_n]
    context = {} if context is None else dict(context)

    candidates = []
    if candidate_df is not None and len(candidate_df) > 0:
        for _, row in candidate_df.iterrows():
            ref_cell_type = row.get("candidate_reference_cell_type")
            if ref_cell_type is None:
                continue
            tissue, cell_type = _split_ref_cell_type(ref_cell_type)
            candidate = row.to_dict()
            candidate["candidate_reference_cell_type"] = str(ref_cell_type)
            candidate["gene_evidence"] = _candidate_gene_evidence(
                ref_cell_type,
                evidenceGeneWeight,
                markerSeries,
                max_genes=max_genes,
            )
            candidate["tissue"] = tissue
            candidate["cell_type"] = cell_type
            candidates.append(candidate)
    else:
        for rank, (ref_cell_type, score) in enumerate(scores.items(), start=1):
            tissue, cell_type = _split_ref_cell_type(ref_cell_type)
            candidate = {
                "rank": rank,
                "ref_cell_type": str(ref_cell_type),
                "tissue": tissue,
                "cell_type": cell_type,
                "score": _json_safe(score),
                "gene_evidence": _candidate_gene_evidence(
                    ref_cell_type,
                    evidenceGeneWeight,
                    markerSeries,
                    max_genes=max_genes,
                ),
            }
            if top_candidate_summary and rank == 1:
                candidate.update(top_candidate_summary)
            candidates.append(candidate)

    if len(candidates) == 0 and len(scores) > 0:
        for rank, (ref_cell_type, score) in enumerate(scores.items(), start=1):
            tissue, cell_type = _split_ref_cell_type(ref_cell_type)
            candidates.append(
                {
                    "rank": rank,
                    "ref_cell_type": str(ref_cell_type),
                    "tissue": tissue,
                    "cell_type": cell_type,
                    "score": _json_safe(score),
                    "gene_evidence": _candidate_gene_evidence(
                        ref_cell_type,
                        evidenceGeneWeight,
                        markerSeries,
                        max_genes=max_genes,
                    ),
                }
            )

    return {
        "context": context,
        "top_cosg_marker_genes": _series_to_gene_records(markerSeries, max_genes=max_genes),
        "candidate_reference_cell_types": candidates,
        "top_candidate_summary": top_candidate_summary,
        "background": background,
    }


def build_marker_gene_score_llm_annotation_prompt(
    marker_gene_scores_cal,
    geneWeight=None,
    markerSeries=None,
    context=None,
    top_n=10,
    max_genes=50,
):
    evidence = build_marker_gene_score_llm_annotation_evidence(
        marker_gene_scores_cal,
        geneWeight=geneWeight,
        markerSeries=markerSeries,
        context=context,
        top_n=top_n,
        max_genes=max_genes,
    )
    evidence_json = json.dumps(evidence, ensure_ascii=False, indent=2)
    return (
        MARKER_GENE_SCORE_ALGORITHM_DESCRIPTION.strip()
        + "\n\nTask:\n"
        + "Evaluate the most likely cell type annotation for the selected cluster. "
        + "Prefer canonical, biologically useful labels over overly specific database "
        + "source labels when the evidence supports that normalization. Identify "
        + "ambiguity and recommend validation genes when needed.\n\n"
        + "Return JSON with these fields: suggested_cell_type, suggested_subtype, "
        + "confidence_score, confidence_label, supporting_markers, conflicting_or_missing_markers, "
        + "alternative_annotations, reasoning_summary, recommended_validation_genes.\n\n"
        + "Evidence:\n"
        + evidence_json
    )


def _unpack_cell_score_plot_result(cell_score_plot_result=None, plotDf=None, marker_cosg=None):
    if cell_score_plot_result is not None:
        if isinstance(cell_score_plot_result, dict):
            plotDf = plotDf if plotDf is not None else cell_score_plot_result.get("plotDf")
            if plotDf is None:
                plotDf = cell_score_plot_result.get("plot_df")
            marker_cosg = marker_cosg if marker_cosg is not None else cell_score_plot_result.get("marker_cosg")
        elif isinstance(cell_score_plot_result, (list, tuple)):
            if len(cell_score_plot_result) > 1 and plotDf is None:
                plotDf = cell_score_plot_result[1]
            if len(cell_score_plot_result) > 2 and marker_cosg is None:
                marker_cosg = cell_score_plot_result[2]

    if plotDf is None:
        plotDf = pd.DataFrame(columns=["score", "cluster"])
    if marker_cosg is None:
        marker_cosg = pd.Series(dtype=float)
    if not isinstance(plotDf, pd.DataFrame):
        plotDf = pd.DataFrame(plotDf)
    if not isinstance(marker_cosg, pd.Series):
        marker_cosg = pd.Series(marker_cosg)

    return plotDf, marker_cosg


def _normalise_marker_dict(markerDict):
    if markerDict is None:
        return {}
    return {str(key): [str(gene) for gene in _as_iterable_genes(genes)] for key, genes in markerDict.items()}


def _as_iterable_genes(value):
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, (list, tuple, pd.Index)):
        return list(value)
    try:
        return list(value)
    except TypeError:
        return [value]


def _score_distribution_records(plotDf, top_n=5):
    required = {"score", "cluster"}
    if len(plotDf) == 0 or not required.issubset(plotDf.columns):
        return []

    score_df = plotDf[list(required)].copy()
    score_df["score"] = pd.to_numeric(score_df["score"], errors="coerce")
    score_df = score_df.dropna(subset=["score", "cluster"])
    if len(score_df) == 0:
        return []

    grouped = score_df.groupby("cluster")["score"]
    summary = grouped.agg(["count", "mean", "median", "min", "max"])
    summary["q1"] = grouped.quantile(0.25)
    summary["q3"] = grouped.quantile(0.75)
    summary = summary.sort_values("median", ascending=False).head(top_n)

    records = []
    for rank, (cluster, row) in enumerate(summary.iterrows(), start=1):
        records.append(
            {
                "rank": rank,
                "candidate_reference_cell_type": str(cluster),
                "cell_count": _json_safe(row["count"]),
                "mean_cell_score": _json_safe(row["mean"]),
                "median_cell_score": _json_safe(row["median"]),
                "q1_cell_score": _json_safe(row["q1"]),
                "q3_cell_score": _json_safe(row["q3"]),
                "min_cell_score": _json_safe(row["min"]),
                "max_cell_score": _json_safe(row["max"]),
            }
        )
    return records


def build_cell_score_llm_annotation_evidence(
    cell_score_plot_result=None,
    plotDf=None,
    marker_cosg=None,
    markerDict=None,
    context=None,
    top_n=5,
    max_genes=50,
):
    plotDf, marker_cosg = _unpack_cell_score_plot_result(
        cell_score_plot_result=cell_score_plot_result,
        plotDf=plotDf,
        marker_cosg=marker_cosg,
    )
    markerDict = _normalise_marker_dict(markerDict)
    context = {} if context is None else dict(context)

    cosg_genes = [str(gene) for gene in marker_cosg.index[:max_genes]]
    cosg_gene_set = set(cosg_genes)
    candidate_records = _score_distribution_records(plotDf, top_n=top_n)

    candidates = []
    for record in candidate_records:
        candidate = record["candidate_reference_cell_type"]
        reference_genes = markerDict.get(candidate, [])
        overlap_genes = [gene for gene in cosg_genes if gene in set(reference_genes)]
        reference_unique_genes = [gene for gene in reference_genes if gene not in cosg_gene_set]
        candidates.append(
            {
                **record,
                "reference_marker_genes": reference_genes[:max_genes],
                "overlap_genes": overlap_genes[:max_genes],
                "reference_unique_genes": reference_unique_genes[:max_genes],
            }
        )

    return {
        "context": context,
        "top_cosg_marker_genes": _series_to_gene_records(marker_cosg, max_genes=max_genes),
        "candidate_reference_cell_types": candidates,
    }


def build_cell_score_llm_annotation_prompt(
    cell_score_plot_result=None,
    plotDf=None,
    marker_cosg=None,
    markerDict=None,
    context=None,
    top_n=5,
    max_genes=50,
):
    evidence = build_cell_score_llm_annotation_evidence(
        cell_score_plot_result=cell_score_plot_result,
        plotDf=plotDf,
        marker_cosg=marker_cosg,
        markerDict=markerDict,
        context=context,
        top_n=top_n,
        max_genes=max_genes,
    )
    evidence_json = json.dumps(evidence, ensure_ascii=False, indent=2)
    return (
        CELL_SCORE_ALGORITHM_DESCRIPTION.strip()
        + "\n\nTask:\n"
        + "Evaluate whether the selected/query cell cluster annotation is supported "
        + "by the buildCellScorePlot cell score distributions. Focus on annotation "
        + "validation: identify the most supported reference cell type, important "
        + "supporting markers, ambiguous alternatives, possible conflicts, and "
        + "recommended validation genes. Use only the provided CellClick evidence.\n\n"
        + "Return JSON with these fields: suggested_reference_cell_type, "
        + "annotation_supported, confidence_score, confidence_label, "
        + "supporting_markers, conflicting_or_missing_markers, "
        + "alternative_reference_cell_types, reasoning_summary, "
        + "recommended_validation_genes.\n\n"
        + "Evidence:\n"
        + evidence_json
    )


def _extract_text_from_response(response):
    if isinstance(response, str):
        return response
    if isinstance(response, dict):
        if "content" in response:
            return response["content"]
        if "text" in response:
            return response["text"]
    if hasattr(response, "output_text"):
        return response.output_text
    if hasattr(response, "choices"):
        choice = response.choices[0]
        if hasattr(choice, "message") and hasattr(choice.message, "content"):
            return choice.message.content
        if hasattr(choice, "text"):
            return choice.text
    return str(response)


def _parse_json_response(text):
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, flags=re.S)
        if match:
            try:
                return json.loads(match.group(0))
            except json.JSONDecodeError:
                pass
    return None


def _call_llm(llm_client, messages, model=None):
    if callable(llm_client):
        kwargs = {"messages": messages}
        if model is not None:
            kwargs["model"] = model
        return llm_client(**kwargs)

    if hasattr(llm_client, "chat") and hasattr(llm_client.chat, "completions"):
        kwargs = {"messages": messages}
        if model is not None:
            kwargs["model"] = model
        return llm_client.chat.completions.create(**kwargs)

    if hasattr(llm_client, "responses"):
        kwargs = {"input": messages}
        if model is not None:
            kwargs["model"] = model
        return llm_client.responses.create(**kwargs)

    raise TypeError("llm_client must be a callable or an OpenAI-compatible client object")


def make_openai_client(api_key=None, base_url=None, timeout=None):
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise ImportError("Install openai to use api_key/base_url directly: pip install openai") from exc

    kwargs = {}
    if api_key is not None:
        kwargs["api_key"] = api_key
    if base_url is not None:
        kwargs["base_url"] = base_url
    if timeout is not None:
        kwargs["timeout"] = timeout
    return OpenAI(**kwargs)


def evaluate_marker_gene_score_annotation(
    marker_gene_scores_cal,
    geneWeight=None,
    markerSeries=None,
    llm_client=None,
    api_key=None,
    base_url=None,
    model=None,
    timeout=None,
    context=None,
    top_n=10,
    max_genes=50,
    standardize=False,
    jaccard_threshold=0.6,
    ols_base_url="https://www.ebi.ac.uk/ols4/api",
    ontology="cl",
    ontology_mapper=None,
):
    prompt = build_marker_gene_score_llm_annotation_prompt(
        marker_gene_scores_cal,
        geneWeight=geneWeight,
        markerSeries=markerSeries,
        context=context,
        top_n=top_n,
        max_genes=max_genes,
    )
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT.strip()},
        {"role": "user", "content": prompt},
    ]

    if llm_client is None and (api_key is not None or base_url is not None):
        llm_client = make_openai_client(api_key=api_key, base_url=base_url, timeout=timeout)

    if llm_client is None:
        result = {
            "messages": messages,
            "prompt": prompt,
            "annotation": None,
            "raw_response": None,
        }
        if standardize:
            result.update(
                _standardize_marker_gene_annotation_result(
                    None,
                    marker_gene_scores_cal,
                    geneWeight=geneWeight,
                    markerSeries=markerSeries,
                    top_n=top_n,
                    max_genes=max_genes,
                    jaccard_threshold=jaccard_threshold,
                    ols_base_url=ols_base_url,
                    ontology=ontology,
                    ontology_mapper=ontology_mapper,
                )
            )
        return result

    raw_response = _call_llm(llm_client, messages, model=model)
    response_text = _extract_text_from_response(raw_response)
    annotation = _parse_json_response(response_text)
    result = {
        "messages": messages,
        "prompt": prompt,
        "annotation": annotation,
        "raw_response": response_text,
    }
    if standardize:
        result.update(
            _standardize_marker_gene_annotation_result(
                annotation,
                marker_gene_scores_cal,
                geneWeight=geneWeight,
                markerSeries=markerSeries,
                top_n=top_n,
                max_genes=max_genes,
                jaccard_threshold=jaccard_threshold,
                ols_base_url=ols_base_url,
                ontology=ontology,
                ontology_mapper=ontology_mapper,
            )
        )
    return result


def _standardize_marker_gene_annotation_result(
    annotation,
    marker_gene_scores_cal,
    geneWeight=None,
    markerSeries=None,
    top_n=10,
    max_genes=50,
    jaccard_threshold=0.6,
    ols_base_url="https://www.ebi.ac.uk/ols4/api",
    ontology="cl",
    ontology_mapper=None,
):
    from scripts.ontology_standardization import standardize_annotation_result

    evidence = build_marker_gene_score_llm_annotation_evidence(
        marker_gene_scores_cal,
        geneWeight=geneWeight,
        markerSeries=markerSeries,
        top_n=top_n,
        max_genes=max_genes,
    )
    standardized = standardize_annotation_result(
        annotation,
        evidence["candidate_reference_cell_types"],
        jaccard_threshold=jaccard_threshold,
        ols_base_url=ols_base_url,
        ontology=ontology,
        mapper=ontology_mapper,
    )
    return {
        "raw_annotation": annotation,
        "standardized_annotation": standardized["standardized_annotation"],
        "merge_report": standardized["merge_report"],
        "top_candidate_summary": evidence.get("top_candidate_summary"),
        "background": evidence.get("background"),
    }


def evaluate_cell_score_annotation(
    cell_score_plot_result=None,
    plotDf=None,
    marker_cosg=None,
    markerDict=None,
    llm_client=None,
    api_key=None,
    base_url=None,
    model=None,
    timeout=None,
    context=None,
    top_n=5,
    max_genes=50,
):
    prompt = build_cell_score_llm_annotation_prompt(
        cell_score_plot_result=cell_score_plot_result,
        plotDf=plotDf,
        marker_cosg=marker_cosg,
        markerDict=markerDict,
        context=context,
        top_n=top_n,
        max_genes=max_genes,
    )
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT.strip()},
        {"role": "user", "content": prompt},
    ]

    if llm_client is None and (api_key is not None or base_url is not None):
        llm_client = make_openai_client(api_key=api_key, base_url=base_url, timeout=timeout)

    if llm_client is None:
        return {
            "messages": messages,
            "prompt": prompt,
            "annotation": None,
            "raw_response": None,
        }

    raw_response = _call_llm(llm_client, messages, model=model)
    response_text = _extract_text_from_response(raw_response)
    return {
        "messages": messages,
        "prompt": prompt,
        "annotation": _parse_json_response(response_text),
        "raw_response": response_text,
    }


def evaluate_processor_marker_gene_score(
    processor,
    cellIDs,
    cellCluster,
    annotationSeries,
    marker_ref_path,
    markerGeneUsed,
    llm_client=None,
    api_key=None,
    base_url=None,
    model=None,
    timeout=None,
    context=None,
    showNum=10,
    cosgParams=None,
    top_n=10,
    max_genes=50,
    standardize=False,
    jaccard_threshold=0.6,
    ols_base_url="https://www.ebi.ac.uk/ols4/api",
    ontology="cl",
    ontology_mapper=None,
):
    marker_gene_scores = MarkerGeneScores_cal(
        processor,
        cellIDs,
        cellCluster,
        annotationSeries,
        marker_ref_path,
        markerGeneUsed,
        showNum=showNum,
        cosgParams=cosgParams,
        return_details=True,
    )
    return evaluate_marker_gene_score_annotation(
        marker_gene_scores,
        llm_client=llm_client,
        api_key=api_key,
        base_url=base_url,
        model=model,
        timeout=timeout,
        context=context,
        top_n=top_n,
        max_genes=max_genes,
        standardize=standardize,
        jaccard_threshold=jaccard_threshold,
        ols_base_url=ols_base_url,
        ontology=ontology,
        ontology_mapper=ontology_mapper,
    )


def evaluate_processor_cell_score(
    processor,
    cellIDs,
    annotation,
    markerDict,
    title,
    layer=None,
    use_raw=False,
    showNum=5,
    geneUsed=5,
    markerUsed=5,
    llm_client=None,
    api_key=None,
    base_url=None,
    model=None,
    timeout=None,
    context=None,
    top_n=5,
    max_genes=50,
):
    figure, plotDf, marker_cosg = processor.buildCellScorePlot(
        cellIDs,
        annotation,
        markerDict,
        title,
        layer=layer,
        use_raw=use_raw,
        showNum=showNum,
        geneUsed=geneUsed,
        markerUsed=markerUsed,
    )
    context = {} if context is None else dict(context)
    context.setdefault("title", title)
    return evaluate_cell_score_annotation(
        plotDf=plotDf,
        marker_cosg=marker_cosg,
        markerDict=markerDict,
        llm_client=llm_client,
        api_key=api_key,
        base_url=base_url,
        model=model,
        timeout=timeout,
        context=context,
        top_n=top_n,
        max_genes=max_genes,
    )


__all__ = [
    "MarkerGeneScores_cal",
    "MARKER_GENE_SCORE_ALGORITHM_DESCRIPTION",
    "CELL_SCORE_ALGORITHM_DESCRIPTION",
    "SYSTEM_PROMPT",
    "make_openai_client",
    "build_marker_gene_score_llm_annotation_evidence",
    "build_marker_gene_score_llm_annotation_prompt",
    "evaluate_marker_gene_score_annotation",
    "evaluate_processor_marker_gene_score",
    "build_cell_score_llm_annotation_evidence",
    "build_cell_score_llm_annotation_prompt",
    "evaluate_cell_score_annotation",
    "evaluate_processor_cell_score",
]
